// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: flightReservations.proto

package proto;

public interface AgencyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.Agency)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string username = 1;</code>
   */
  java.lang.String getUsername();
  /**
   * <code>string username = 1;</code>
   */
  com.google.protobuf.ByteString
      getUsernameBytes();

  /**
   * <code>string password = 2;</code>
   */
  java.lang.String getPassword();
  /**
   * <code>string password = 2;</code>
   */
  com.google.protobuf.ByteString
      getPasswordBytes();
}
