// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: flightReservations.proto

package proto;

public interface ClientOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.Client)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   */
  int getId();

  /**
   * <code>string firstName = 2;</code>
   */
  java.lang.String getFirstName();
  /**
   * <code>string firstName = 2;</code>
   */
  com.google.protobuf.ByteString
      getFirstNameBytes();

  /**
   * <code>string lastName = 3;</code>
   */
  java.lang.String getLastName();
  /**
   * <code>string lastName = 3;</code>
   */
  com.google.protobuf.ByteString
      getLastNameBytes();

  /**
   * <code>string address = 4;</code>
   */
  java.lang.String getAddress();
  /**
   * <code>string address = 4;</code>
   */
  com.google.protobuf.ByteString
      getAddressBytes();
}
