// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: flightReservations.proto

package proto;

public interface FlightOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.Flight)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   */
  int getId();

  /**
   * <code>string destination = 2;</code>
   */
  java.lang.String getDestination();
  /**
   * <code>string destination = 2;</code>
   */
  com.google.protobuf.ByteString
      getDestinationBytes();

  /**
   * <code>string date = 3;</code>
   */
  java.lang.String getDate();
  /**
   * <code>string date = 3;</code>
   */
  com.google.protobuf.ByteString
      getDateBytes();

  /**
   * <code>string time = 4;</code>
   */
  java.lang.String getTime();
  /**
   * <code>string time = 4;</code>
   */
  com.google.protobuf.ByteString
      getTimeBytes();

  /**
   * <code>string airport = 5;</code>
   */
  java.lang.String getAirport();
  /**
   * <code>string airport = 5;</code>
   */
  com.google.protobuf.ByteString
      getAirportBytes();

  /**
   * <code>int32 places = 6;</code>
   */
  int getPlaces();
}
