// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: flightReservations.proto

package proto;

public interface GetByDestAndDateRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.GetByDestAndDateRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string destination = 1;</code>
   */
  java.lang.String getDestination();
  /**
   * <code>string destination = 1;</code>
   */
  com.google.protobuf.ByteString
      getDestinationBytes();

  /**
   * <code>string date = 2;</code>
   */
  java.lang.String getDate();
  /**
   * <code>string date = 2;</code>
   */
  com.google.protobuf.ByteString
      getDateBytes();
}
