// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: flightReservations.proto

package proto;

public interface LoginResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.LoginResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool successful = 1;</code>
   */
  boolean getSuccessful();
}
