// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: flightReservations.proto

package proto;

public interface TicketOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.Ticket)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   */
  int getId();

  /**
   * <code>int32 clientId = 2;</code>
   */
  int getClientId();

  /**
   * <code>int32 flightId = 3;</code>
   */
  int getFlightId();

  /**
   * <code>string touristFirstName = 4;</code>
   */
  java.lang.String getTouristFirstName();
  /**
   * <code>string touristFirstName = 4;</code>
   */
  com.google.protobuf.ByteString
      getTouristFirstNameBytes();

  /**
   * <code>string touristLastName = 5;</code>
   */
  java.lang.String getTouristLastName();
  /**
   * <code>string touristLastName = 5;</code>
   */
  com.google.protobuf.ByteString
      getTouristLastNameBytes();
}
