// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: flightReservations.proto

package proto;

/**
 * Protobuf type {@code proto.Ticket}
 */
public  final class Ticket extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:proto.Ticket)
    TicketOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Ticket.newBuilder() to construct.
  private Ticket(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Ticket() {
    touristFirstName_ = "";
    touristLastName_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Ticket(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            id_ = input.readInt32();
            break;
          }
          case 16: {

            clientId_ = input.readInt32();
            break;
          }
          case 24: {

            flightId_ = input.readInt32();
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            touristFirstName_ = s;
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            touristLastName_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return proto.FlightReservationsProto.internal_static_proto_Ticket_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return proto.FlightReservationsProto.internal_static_proto_Ticket_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            proto.Ticket.class, proto.Ticket.Builder.class);
  }

  public static final int ID_FIELD_NUMBER = 1;
  private int id_;
  /**
   * <code>int32 id = 1;</code>
   */
  public int getId() {
    return id_;
  }

  public static final int CLIENTID_FIELD_NUMBER = 2;
  private int clientId_;
  /**
   * <code>int32 clientId = 2;</code>
   */
  public int getClientId() {
    return clientId_;
  }

  public static final int FLIGHTID_FIELD_NUMBER = 3;
  private int flightId_;
  /**
   * <code>int32 flightId = 3;</code>
   */
  public int getFlightId() {
    return flightId_;
  }

  public static final int TOURISTFIRSTNAME_FIELD_NUMBER = 4;
  private volatile java.lang.Object touristFirstName_;
  /**
   * <code>string touristFirstName = 4;</code>
   */
  public java.lang.String getTouristFirstName() {
    java.lang.Object ref = touristFirstName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      touristFirstName_ = s;
      return s;
    }
  }
  /**
   * <code>string touristFirstName = 4;</code>
   */
  public com.google.protobuf.ByteString
      getTouristFirstNameBytes() {
    java.lang.Object ref = touristFirstName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      touristFirstName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TOURISTLASTNAME_FIELD_NUMBER = 5;
  private volatile java.lang.Object touristLastName_;
  /**
   * <code>string touristLastName = 5;</code>
   */
  public java.lang.String getTouristLastName() {
    java.lang.Object ref = touristLastName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      touristLastName_ = s;
      return s;
    }
  }
  /**
   * <code>string touristLastName = 5;</code>
   */
  public com.google.protobuf.ByteString
      getTouristLastNameBytes() {
    java.lang.Object ref = touristLastName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      touristLastName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (id_ != 0) {
      output.writeInt32(1, id_);
    }
    if (clientId_ != 0) {
      output.writeInt32(2, clientId_);
    }
    if (flightId_ != 0) {
      output.writeInt32(3, flightId_);
    }
    if (!getTouristFirstNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, touristFirstName_);
    }
    if (!getTouristLastNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, touristLastName_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (id_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, id_);
    }
    if (clientId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, clientId_);
    }
    if (flightId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, flightId_);
    }
    if (!getTouristFirstNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, touristFirstName_);
    }
    if (!getTouristLastNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, touristLastName_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof proto.Ticket)) {
      return super.equals(obj);
    }
    proto.Ticket other = (proto.Ticket) obj;

    if (getId()
        != other.getId()) return false;
    if (getClientId()
        != other.getClientId()) return false;
    if (getFlightId()
        != other.getFlightId()) return false;
    if (!getTouristFirstName()
        .equals(other.getTouristFirstName())) return false;
    if (!getTouristLastName()
        .equals(other.getTouristLastName())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId();
    hash = (37 * hash) + CLIENTID_FIELD_NUMBER;
    hash = (53 * hash) + getClientId();
    hash = (37 * hash) + FLIGHTID_FIELD_NUMBER;
    hash = (53 * hash) + getFlightId();
    hash = (37 * hash) + TOURISTFIRSTNAME_FIELD_NUMBER;
    hash = (53 * hash) + getTouristFirstName().hashCode();
    hash = (37 * hash) + TOURISTLASTNAME_FIELD_NUMBER;
    hash = (53 * hash) + getTouristLastName().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static proto.Ticket parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static proto.Ticket parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static proto.Ticket parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static proto.Ticket parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static proto.Ticket parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static proto.Ticket parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static proto.Ticket parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static proto.Ticket parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static proto.Ticket parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static proto.Ticket parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static proto.Ticket parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static proto.Ticket parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(proto.Ticket prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code proto.Ticket}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:proto.Ticket)
      proto.TicketOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.FlightReservationsProto.internal_static_proto_Ticket_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.FlightReservationsProto.internal_static_proto_Ticket_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proto.Ticket.class, proto.Ticket.Builder.class);
    }

    // Construct using proto.Ticket.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      id_ = 0;

      clientId_ = 0;

      flightId_ = 0;

      touristFirstName_ = "";

      touristLastName_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return proto.FlightReservationsProto.internal_static_proto_Ticket_descriptor;
    }

    @java.lang.Override
    public proto.Ticket getDefaultInstanceForType() {
      return proto.Ticket.getDefaultInstance();
    }

    @java.lang.Override
    public proto.Ticket build() {
      proto.Ticket result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public proto.Ticket buildPartial() {
      proto.Ticket result = new proto.Ticket(this);
      result.id_ = id_;
      result.clientId_ = clientId_;
      result.flightId_ = flightId_;
      result.touristFirstName_ = touristFirstName_;
      result.touristLastName_ = touristLastName_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof proto.Ticket) {
        return mergeFrom((proto.Ticket)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(proto.Ticket other) {
      if (other == proto.Ticket.getDefaultInstance()) return this;
      if (other.getId() != 0) {
        setId(other.getId());
      }
      if (other.getClientId() != 0) {
        setClientId(other.getClientId());
      }
      if (other.getFlightId() != 0) {
        setFlightId(other.getFlightId());
      }
      if (!other.getTouristFirstName().isEmpty()) {
        touristFirstName_ = other.touristFirstName_;
        onChanged();
      }
      if (!other.getTouristLastName().isEmpty()) {
        touristLastName_ = other.touristLastName_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      proto.Ticket parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (proto.Ticket) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int id_ ;
    /**
     * <code>int32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }
    /**
     * <code>int32 id = 1;</code>
     */
    public Builder setId(int value) {
      
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 id = 1;</code>
     */
    public Builder clearId() {
      
      id_ = 0;
      onChanged();
      return this;
    }

    private int clientId_ ;
    /**
     * <code>int32 clientId = 2;</code>
     */
    public int getClientId() {
      return clientId_;
    }
    /**
     * <code>int32 clientId = 2;</code>
     */
    public Builder setClientId(int value) {
      
      clientId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 clientId = 2;</code>
     */
    public Builder clearClientId() {
      
      clientId_ = 0;
      onChanged();
      return this;
    }

    private int flightId_ ;
    /**
     * <code>int32 flightId = 3;</code>
     */
    public int getFlightId() {
      return flightId_;
    }
    /**
     * <code>int32 flightId = 3;</code>
     */
    public Builder setFlightId(int value) {
      
      flightId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 flightId = 3;</code>
     */
    public Builder clearFlightId() {
      
      flightId_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object touristFirstName_ = "";
    /**
     * <code>string touristFirstName = 4;</code>
     */
    public java.lang.String getTouristFirstName() {
      java.lang.Object ref = touristFirstName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        touristFirstName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string touristFirstName = 4;</code>
     */
    public com.google.protobuf.ByteString
        getTouristFirstNameBytes() {
      java.lang.Object ref = touristFirstName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        touristFirstName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string touristFirstName = 4;</code>
     */
    public Builder setTouristFirstName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      touristFirstName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string touristFirstName = 4;</code>
     */
    public Builder clearTouristFirstName() {
      
      touristFirstName_ = getDefaultInstance().getTouristFirstName();
      onChanged();
      return this;
    }
    /**
     * <code>string touristFirstName = 4;</code>
     */
    public Builder setTouristFirstNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      touristFirstName_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object touristLastName_ = "";
    /**
     * <code>string touristLastName = 5;</code>
     */
    public java.lang.String getTouristLastName() {
      java.lang.Object ref = touristLastName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        touristLastName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string touristLastName = 5;</code>
     */
    public com.google.protobuf.ByteString
        getTouristLastNameBytes() {
      java.lang.Object ref = touristLastName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        touristLastName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string touristLastName = 5;</code>
     */
    public Builder setTouristLastName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      touristLastName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string touristLastName = 5;</code>
     */
    public Builder clearTouristLastName() {
      
      touristLastName_ = getDefaultInstance().getTouristLastName();
      onChanged();
      return this;
    }
    /**
     * <code>string touristLastName = 5;</code>
     */
    public Builder setTouristLastNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      touristLastName_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:proto.Ticket)
  }

  // @@protoc_insertion_point(class_scope:proto.Ticket)
  private static final proto.Ticket DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new proto.Ticket();
  }

  public static proto.Ticket getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Ticket>
      PARSER = new com.google.protobuf.AbstractParser<Ticket>() {
    @java.lang.Override
    public Ticket parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Ticket(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Ticket> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Ticket> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public proto.Ticket getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

