// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: flightReservations.proto

package proto;

public interface UpdateResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.UpdateResponse)
    com.google.protobuf.MessageOrBuilder {
}
