// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: flightReservations.proto

package proto;

public interface VoidOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.Void)
    com.google.protobuf.MessageOrBuilder {
}
